[project]
name = "configurize"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "loguru",
    "fire",
]

[project.scripts]
cfshow = "configurize.cli:main"
